//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examschema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam1()
        {
            this.Students = new HashSet<Student1>();
        }
    
        public int ExamCode { get; set; }
        public string ExamName { get; set; }
        public string ExamDate { get; set; }
        public string MaxMarks { get; set; }
        public string CutOff { get; set; }
        public string Duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student1> Students { get; set; }
    }
}
