//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examschema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Result1
    {
        public int StNo { get; set; }
        public int SecMarks { get; set; }
        public int MaxMarks { get; set; }
        public float Percentage { get; set; }
    }
}
