//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examschema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student1
    {
        public int StNo { get; set; }
        public string StName { get; set; }
        public string ExamDt { get; set; }
        public int ExamCode { get; set; }
        public int Sid { get; set; }
    
        public virtual Exam1 Exam { get; set; }
        public virtual School1 School { get; set; }
    }
}
